### ISSUE TITLE
Bug Report : GraphQLError: Syntax Error: Unexpected <EOF> causes failure in typechecking

### ISSUE THREAD

**Issue by bandhan-majumder** [PalisadoesFoundation/talawa-api#2769] opened 2024-12-17 19:28 UTC
**Describe the bug**
When a new PR is submitted, due to pre-existing error in graphql syntax, in the first step `Check for linting, formatting, and type errors` at `Run Typescript Type-Checker`, the graphql syntax error comes and causes failure in the workflow. We can also reproduce this in our local enviornment with the below steps.

**To Reproduce**

1. Go to develop branch
2. Run `npm run typecheck`

**Expected behavior**
It should pass

**Actual behavior**
It's failing

**Screenshots**
![image](https://github.com/user-attachments/assets/1cae5568-d796-4702-9dca-8f4e0248af6d)

**Additional details**
All the PRs are failing this test.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prayanshchh** [comment] 2024-12-18 06:15
check this out

https://github.com/redwoodjs/redwood/issues/9195
https://github.com/redwoodjs/redwood/pull/9140

**Comment by prayanshchh** [comment] 2024-12-18 06:28
assign

**Comment by Aad1tya27** [comment] 2024-12-18 06:42
The problem is in unions.ts, it has an empty gql block. I had included this change in my pr, if it's acceptable then I can link both issues to my pr.

**Comment by prayanshchh** [comment] 2024-12-19 04:29
yes that file wasn't needed, removing it solves the issue...I did it in my PR

**Comment by bandhan-majumder** [comment] 2024-12-19 05:55
Waiting for the PR to merge so that other PRs can pass that test.

**Comment by akshayw1** [comment] 2024-12-19 14:18
Pls assign

**Comment by Cioppolo14** [comment] 2024-12-19 16:59
@Aad1tya27 I'm assigning this to you as an exception so it can be resolves through your open PR.

**Closed** 2024-12-20 01:27 UTC
Labels: bug, test
