### ISSUE TITLE
Fix the mutation input types

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1211] opened 2023-03-21 10:56 UTC
**Describe the bug**

https://github.com/PalisadoesFoundation/talawa-api/pull/1168#issuecomment-1465270002

Accept a single argument named input of type UpdateOrganizationInput, include the organization's id within that and make the id required. Also make the input required in mutation definition like this input: UpdateOrganizationInput!. It doesn't make sense to make a mutation request without the input object.

Mutation receiving a single argument named input is the convention in graphql. It's a good practice to stick to conventions.

Fixes the types and refactors the arguments for `updateOrganization` , `createPost` and other mutations when needed as directed by @xoldyckk  
**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment] 2023-03-21 10:56
Pls assign this to me

**Comment by kb-0311** [comment] 2023-03-21 11:21
@palisadoes done.

**Comment by palisadoes** [comment] 2023-03-21 11:31
Please fix the title

**Comment by kb-0311** [comment] 2023-03-22 05:59
@palisadoes pls assign this to me

**Comment by Dougsworth** [comment] 2023-06-03 01:00
Describe the Bug:
The issue pertains to a bug in the GraphQL API. The current implementation of certain mutations, including updateOrganization and createPost, does not adhere to the GraphQL convention of accepting a single argument named input.

Expected Behavior:
The expected behavior is for these mutations to accept a single argument named input of type UpdateOrganizationInput. The id of the organization should be included within this input and should be required. The input itself should also be required in the mutation definition, i.e., input: UpdateOrganizationInput!. This is because it doesn't make sense to make a mutation request without the input object.

Actual Behavior:
The actual behavior of the code is not described in detail in the issue, but it seems that the mutations are not following the expected GraphQL conventions, leading to potential issues.

Solution:
The solution involves fixing the types and refactoring the arguments for the updateOrganization, createPost, and any other affected mutations. This should be done as directed by @xoldyckk, who appears to be a contributor or maintainer of the repository. The mutations should be refactored to accept a single input argument, and both the id and input should be required.

**Comment by palisadoes** [comment] 2023-06-04 13:15
@Dougsworth Do you want to work on this?

**Comment by palisadoes** [comment] 2023-06-04 13:31
@kb-0311 Thanks for closing the PR to allow @Dougsworth to give this a try

**Comment by palisadoes** [comment] 2023-06-27 20:36
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Closed** 2023-07-10 16:48 UTC
Labels: bug, feature request, no-issue-activity
