### ISSUE TITLE
Comparision b/w type ObjectId and String

### ISSUE THREAD

**Issue by akshatgarg12** [PalisadoesFoundation/talawa-api#275] opened 2021-05-25 17:01 UTC
**Describe the bug**
A lot of resolvers are failing because of the comparison between a mongoose objectId type and a string.
**To Reproduce**

1. use the remove member mutation and then check the organisation members (resolver doesn't work) 
2. Many such places where (type ObjectId === type String) is being used is failing)

**Expected behavior**
The query should resolve and the data should be changed.

**Actual behavior**
Sometimes the query is resolved but the data is not changed due to the bug in filter 

**Additional details**
Can be resolved by using .equals() method or by converting to string by .toString() method and then comparing.
This will help in minimizing errors and will make the checks consistent.
for more info : https://stackoverflow.com/questions/11637353/comparing-mongoose-id-and-strings

**Comment by saymedgm** [comment] 2021-07-16 11:55
@palisadoes please assign me this issue

**Comment by Sagar2366** [comment] 2021-07-16 12:59
@saymedgm can you please try to reproduce the issue first. If the issue is still not fixed you can work on it.

**Comment by saymedgm** [comment] 2021-07-16 13:21
ok

**Comment by uzair-ali10** [comment] 2021-08-06 21:08
I Can see that this hasn't been resolved yet. I encountered the same problem while resolving #276 . I was comparing user ID from the MongoDB document and `args.data.organizationId` with `===` however later I found that I was supposed to use `.equals()` 
For Eg:


Wrong:
* `orgID===(args.data.organizationId)`
Right:
* `orgID.equals(args.data.organizationId)`

As mention by the issue creator I can see in [member_mutations/removeMember.js](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/resolvers/member_mutations/removeMember.js)
on line No 48 it is coded as `org._doc.creator === user.id` instead it should be `org._doc.creator.equals(user.id)`

So I presume remove member mutations is also not working due to this


Can u please assign this issue to me and also bring other such broken mutations into my notice so that I may resolve them.

**Comment by uzair-ali10** [comment] 2021-08-10 09:55
@akshatgarg12 
Can you bring more such broken mutations into my notice, So that I may resolve them

**Comment by akshatgarg12** [comment] 2021-08-10 15:07
> @akshatgarg12 
> Can you bring more such broken mutations into my notice, So that I may resolve them

Hey I don't have a record of it, I would suggest you to use VS-Code search/find feature to find such instances and change them.

**Comment by uzair-ali10** [comment] 2021-08-11 04:00
> > @akshatgarg12
> > Can you bring more such broken mutations into my notice, So that I may resolve them
> 
> Hey I don't have a record of it, I would suggest you to use VS-Code search/find feature to find such instances and change them.

Ohh Okay, No issue!!

**Comment by palisadoes** [comment] 2021-11-26 17:34
@uzair-ali10, @akshatgarg12, @sumitra19jha  I have found `185` instances of this in the current code base. Shouldn't we be correcting all the instances.

```
$ cd talawa-api
$ grep -ir '===' . | wc -l
```

**Comment by sumitra19jha** [comment] 2021-11-26 17:56
Yes, I think we should make it consistent across entire code base.

**Comment by uzair-ali10** [comment] 2021-11-26 17:57
> @uzair-ali10, @akshatgarg12, @sumitra19jha I have found `185` instances of this in the current code base. Shouldn't we be correcting all the instances?
> 
> ```
> $ cd talawa-api
> $ grep -ir '===' . | wc -l
> ```

I'll raise PR for the following

**Closed** 2022-12-03 10:58 UTC
Labels: bug
