### ISSUE TITLE
Organization doesn't have id of creator

### ISSUE THREAD

**Issue by Laurell876** [PalisadoesFoundation/talawa-api#160] opened 2021-03-17 14:02 UTC
When created the company does not hold the _id of the creator which makes it inefficient to check whether the logged in user is the admin of organization or not

**Comment by Gautam-Arora24** [comment] 2021-03-17 14:07
@Laurell876 I want to work on this issue. Can you please assign it to me?

**Comment by CyberWake** [comment] 2021-03-18 02:47
@Laurell876 sir please assign this to me. I have taken the insights of the following issue. Remarked the same as well after making points on frontend requirement. I felt this as a issue while working on the same issue to fix the issue over there. Found that is requires some changes in talawa-api as well to have it a flawless one.

**Comment by CyberWake** [comment] 2021-03-18 02:48
Would like to working on this one ☺️.

**Comment by Priyaraj17** [comment] 2021-03-19 06:40
Is this issue still open? May I work on this?

**Comment by CyberWake** [comment] 2021-03-20 17:55
the issue is resolved we may close this one @Laurell876 sir.

**Comment by CyberWake** [comment] 2021-03-20 17:58
with the merge of the PR #162

**Closed** 2021-05-22 18:06 UTC
Labels: bug, unapproved
