### ISSUE TITLE
Org Admins must be able to edit member information for their organizations

### ISSUE THREAD

**Issue by Anvita0305** [PalisadoesFoundation/talawa-api#1752] opened 2024-01-28 14:47 UTC
**Describe the bug**
1. The Admin of an Organization must be able to change other members role.
2. Currently only the SuperAdmin is able to do so.

**Expected behavior**
1. The admin must also be able to change the roles of the members

**Actual behavior**
1. Only superadmin is able to update the roles in the org, not the admin.

**Screenshots**
This is the screenshot from Admin portal. Whenever the admin tries to update the role, this error is encountered.
![Screenshot from 2024-01-28 19-52-08](https://github.com/PalisadoesFoundation/talawa-api/assets/78889572/f32b4e87-901e-4f61-ad0d-6abc764cb4ed)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by jayantpranjal0** [comment] 2024-01-29 21:24
@palisadoes Can I work on this issue?

**Comment by Cioppolo14** [comment] 2024-02-10 00:49
Unassigning due to no activity or PR.

**Comment by MSVaibhav4141** [comment] 2024-02-10 03:16
@Cioppolo14 
Sir,I already have two assigned issues; I believe one of them is a duplicate, and the other one is assigned to me. Could you please review the issue [#1697](https://github.com/PalisadoesFoundation/talawa-api/issues/1697) assigned to me and reassign me to the issue referenced within that task? This way, I would be left with only one workable issue. 
So sir Can I work on this issue?

**Comment by Cioppolo14** [comment] 2024-02-10 14:05
@MSVaibhav4141 I closed the duplicate.  In the future, you can unassign yourself, please just leave a comment that you are doing so, it helps us keep tracking.  Thank you!

**Comment by MSVaibhav4141** [comment] 2024-02-19 17:03
Working on it

**Comment by MSVaibhav4141** [comment] 2024-02-20 18:20
@Anvita0305 Have you worked on it ? I may need a slight assistance

**Comment by MSVaibhav4141** [comment] 2024-02-20 18:41
@Cioppolo14  I have tried to change **superAdminCheck()** to normal **adminCheck()** under 

> src\resolvers\Mutation\createAdmin.ts
_on line 67_

like this 
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/106318667/af7d68b2-0f51-4379-a8a5-21fe266d57e8)

But then also it's still throwing me the same error on adding a user to admin with admin previlage
This is the error **user not authorized**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/106318667/090e113f-fb61-4a10-8fb4-e9228888d3f0)

any assistance would be greatly appreciated.
Thanks:)

**Comment by Anvita0305** [comment] 2024-02-21 02:41
> @Anvita0305 Have you worked on it ? I may need a slight assistance

No @MSVaibhav4141 , I have worked on the frontend.

**Comment by MSVaibhav4141** [comment] 2024-02-21 09:03
> > @Anvita0305 Have you worked on it ? I may need a slight assistance
> 
> No @MSVaibhav4141 , I have worked on the frontend.

@Anvita0305 
 Ohkk.. however any suggestions on the issue I am facing

**Comment by palisadoes** [comment] 2024-03-03 00:23
1. Unassigning due to inactivity. No submitted PR
1. This is open for reassignment, preferably to someone with an active GitHub profile on the technologies used or experience with the repository

**Comment by ryuga001** [comment] 2024-03-04 07:17
@palisadoes Can I work on this issue?

**Comment by palisadoes** [comment] 2024-03-15 01:18
Unassigning, not activity or PR

**Comment by Anubhav-2003** [comment] 2024-03-16 06:36
@palisadoes I would like to work on this issue.

**Comment by Anubhav-2003** [comment] 2024-03-20 07:45
@palisadoes Respected sir, I have a query, should we allow one admin to assign a user as an admin for an organization? Because that is basically what this issue has been created about. Because according to my understanding a person of the same portfolio should not be able to promote someone to the same status, or in other words I feel an admin should not have the power to assign another person as admin.

It should only be the superadmin. What is your take on this.

Thank You.

**Comment by Anubhav-2003** [comment] 2024-03-22 16:25
@palisadoes Respected sir, I don't think this issue is needed, as there are only three Roles "SUPERADMIN", "ADMIN", and "USER". And an Admin should not be able to Promote an "USER", to an "Admin". And this is correctly implemented in the resolver "updateUserRoleInOrganization.ts". Please tell me if I am missing something, or else I would suggest closing this issue as unplanned. 

Thank You.

**Comment by Anvita0305** [comment] 2024-03-22 18:16
Hey @Anubhav-2003, I had created this issue based on the information available here https://docs.talawa.io/docs/introduction/core-concepts. I have also attached screenshot for reference.
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/78889572/bc3b9d1d-7cb7-4ebf-81c1-3fa88217d287)
Hope it helps!

**Comment by Anubhav-2003** [comment] 2024-03-23 06:23
@Anvita0305 ok anvita, thanks for the help.

**Comment by Anubhav-2003** [comment] 2024-03-26 10:44
unassigned myself, as this issue cannot be solved unless this issue https://github.com/PalisadoesFoundation/talawa-api/issues/2084 and https://github.com/PalisadoesFoundation/talawa-admin/issues/1765 are solved. I have solved the first one. Once its PR is merged, I will come back. Thank You.

**Comment by pranshugupta54** [comment] 2024-04-11 17:02
Can not reproduce, it works properly.

- Tried changing the role from USER to ADMIN and vice-versa using Admin's authentication and works perfectly.

<img width="1115" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/eef1853f-6a04-4ff8-8802-5134f0cb30df">


Note: If you are talking about the issue on frontend, then the design is changed and yet to be completed. Currently admins dont have a way to change role, it will be implemented soon.

**Comment by palisadoes** [comment] 2024-04-11 22:27
Closing. Covered here

1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1885

**Closed by palisadoes** 2024-04-11 22:27 UTC
Labels: bug
