### ISSUE TITLE
Feature Request: Implement GraphQL Error Handling: Resolver user

### ISSUE THREAD

**Issue by Sivam2313** [PalisadoesFoundation/talawa-api#1474] opened 2023-12-08 07:26 UTC
Parent: #1450 
**Is your feature request related to a problem? Please describe.**
Implement Error handling in user resolver as mentioned in #1450.

**Describe the solution you'd like**
We can set the return type of user resolver to ```UserResult``` which will contain the ```data``` and ```errors``` . ```errors``` can be ```UserNotFoundError``` or ```UnauthenticatedError```. The ```UnauthenticatedError``` can come from authdirective. Then we can handle all these errors in the client side.

**Comment by Sivam2313** [comment] 2023-12-08 07:27
I would like to work on this.

**Comment by palisadoes** [comment] 2023-12-19 03:51
Unassigning due to inactivity and no open PRs

**Comment by Veer0x1** [comment] 2023-12-19 07:09
@palisadoes I would like to work on it.

**Comment by Veer0x1** [comment] 2023-12-22 18:19
I'm working on this, its taking time, cause I'm learning graphql

**Comment by shankeleven** [comment] 2024-01-05 04:58
please assign this to me, i would be happy to help

**Comment by Veer0x1** [comment] 2024-01-05 06:00
> please assign this to me, i would be happy to help

@shankeleven the parent issue has been closed.

**Comment by varshith257** [comment] 2024-01-10 14:18
@noman2002 @Ayush0Chaudhary @Kevoniat @sumitra19jha @nishnatadebnath 

If it is yet unassigned. Looking forward to work on this Open issue

**Comment by varshith257** [comment] 2024-01-10 14:20
@noman2002 @Kevoniat @sumitra19jha @nishnatadebnath

If it is yet unassigned. Looking forward to work on this Open issue

**Comment by NamitBhutani** [comment] 2024-01-10 18:04
If the issue is unassigned, I'd like to work on it!

**Comment by NayOoLwin5** [comment] 2024-01-16 14:36
I would like to work on it. Pls assign it to me.

**Comment by Cioppolo14** [comment] 2024-01-17 01:40
This needs to be closed, since its parent issue is closed.

**Closed** 2024-01-17 01:40 UTC
Labels: feature request, parent
