### ISSUE TITLE
Cannot create events on locally hosted MongoDB instance

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2104] opened 2024-03-26 21:15 UTC
**Describe the bug**

1. This issue has resurfaced. You cannot create events in Talawa-Admin because of this error
2. It was previously fixed in the issue below. 
3. This is probably caused by the updates in the `develop` branch after the merge from the `develop-userTypeFix` branch

**To Reproduce**

1. Login as any user
2. Try to create an event
3. The action fails, and you get a toast error message.

**Expected behavior**

1. Events can be created using either a cloud or local mongoDB instance
2. A test is created to test this functionality. 
    1. This is the second time that we have noticed this. 
    2. It should not have been repeated 

**Actual behavior**

- See screenshot when an an attempt to create an event occurs

**Screenshots**

1. You cannot create events

    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/b8e5ed06-7526-489d-bafe-b2ae40ab1809)

1. You cannot view organization people

    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/3b341a89-2d7f-4127-936f-cf6b4e0a93b9)

**Additional details**

- https://github.com/PalisadoesFoundation/talawa-api/issues/1772

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by meetulr** [comment] 2024-03-27 01:32
@palisadoes the event creation is failing because of a schema change i made in my api pr the other day. I'm sorry i should have mentioned it there😅.

I have fixed it as part of my next pr in admin. I'll raise the pr soon.

**Comment by palisadoes** [comment] 2024-03-27 02:43
Can you view organization people on a local DB?

**Comment by meetulr** [comment] 2024-03-27 03:56
1) I have fixed event creation in this pr [link](https://github.com/PalisadoesFoundation/talawa-admin/pull/1817)

2) On people screen, it says member not found and 400 error, this too is happening most likely because of recent schema changes, there are open issues addressing this.

**Comment by AdityaRaimec22** [comment] 2024-03-27 08:14
@palisadoes  It is duplicate of #2029.

**Comment by meetulr** [comment] 2024-03-27 10:04
No @AdityaRaimec22 this is caused by a most recent change as I mentioned, i.e. because of schema discrepancies. The error is dirrerent from the issue the you mentioned.

**Closed** 2024-03-27 11:54 UTC
Labels: bug, unapproved, userTypeFix
