### ISSUE TITLE
 Resolvers: Create tests for src/lib/directives/authDirective.ts

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#797] opened 2022-12-05 04:07 UTC
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/lib/directives/authDirective.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `talawa-api/__tests__/directives/authDirective.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/c691d5377f98da582d7b0c1f930b9ec657f5274e/src/lib/directives/authDirective.ts). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by MaYaNkKashyap681** [comment] 2023-01-05 07:20
Sir, as a beginner, can I work on this issue,
What are all the prerequisites to start the contribution?

**Comment by palisadoes** [comment] 2023-01-05 18:57
Thanks @MaYaNkKashyap681 

1. You can read the [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/CONTRIBUTING.md) file for guidance. 
2. You can also contact past contributors like @SiddheshKukade in this thread, or in our slack channel. The link is in the [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/CONTRIBUTING.md) file too

**Comment by MaYaNkKashyap681** [comment] 2023-01-05 19:42
Is there any deadline?

**Comment by palisadoes** [comment] 2023-01-05 19:50
Issues are automatically labeled unassigned `[no-issue-activity](https://github.com/PalisadoesFoundation/talawa-api/labels/no-issue-activity)` after 90 days of inactivity. We'd prefer a resolution within a month.

**Comment by MaYaNkKashyap681** [comment] 2023-01-05 20:01
> prefer a resolution

ok

**Comment by MaYaNkKashyap681** [comment] 2023-01-07 17:40
Sir,
1).  Is the description of the issue wrong, do I need to write the test for lib/helper_functions/authDirective.js,
It should be helper_function/deleteImage.js. and the test should be written in  tests/helper_functions/deleteImage.spec.js.

2). when I am cloning the master branch, tests/helper_function is not there, instead, there is tests/function, are both the same, or am I cloning a different branch, and I have to write a test for lib/helper_functions/  but the folder helper_function is not inside lib folder

**Comment by palisadoes** [comment] 2023-01-08 01:42
@SiddheshKukade Please provide feedback.

**Comment by beingnoble03** [comment] 2023-01-08 06:39
@MaYaNkKashyap681 yes, you are right. There is a different issue for `authDirective.ts`. The path written here, was before the typescript migration. `src/lib/utilities/deleteImage.ts` would be the correct path here. You will need to write tests in the file `__tests__/utilities/deleteImage.spec.ts`.

**Comment by SiddheshKukade** [comment] 2023-01-08 10:22
> Sir, 1). Is the description of the issue wrong, do I need to write the test for lib/helper_functions/authDirective.js, I think It should be helper_function/deleteImage.js. and the test should be written in tests/helper_functions/deleteImage.spec.js.
> 
> 2). when I am cloning the master branch, tests/helper_function is not there, instead, there is tests/function, are both the same, or am I cloning a different branch, and I have to write a test for lib/helper_functions/ but the folder helper_function is not inside lib folder

@MaYaNkKashyap681 Hello, 
The correct paths for this file are now updated in the issue description. 
You can view the latest code coverage for that file [here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/c691d5377f98da582d7b0c1f930b9ec657f5274e/src/lib/directives/authDirective.ts) .
Make sure your repository is synced and updated with the latest commit. 
You can now find the path for this file in `src/lib/directives/authDirective.ts `.
You have to add the test files in `talawa-api/__tests__/directives/authDirective.spec.ts`

**Comment by beingnoble03** [comment] 2023-01-08 11:30
@SiddheshKukade I think we should change the title to previous one, because now this issue has turned into a duplicate issue of #793

**Comment by MaYaNkKashyap681** [comment] 2023-01-08 12:10
Please make things clear, all this is confusing me a lot.

**Comment by MaYaNkKashyap681** [comment] 2023-01-08 12:11
> Please make things clear, all this is confusing me a lot.

can you assign me any issue other than this??

**Comment by MaYaNkKashyap681** [comment] 2023-01-10 16:54
Please update things, so that i can contribute.

**Comment by noman2002** [comment] 2023-01-29 11:10
duplicate of #920

**Closed by noman2002** 2023-01-29 11:10 UTC
Labels: good first issue, points 01, test
