### ISSUE TITLE
Bug: Can only fetch `_id` from the sub documents of `User` collection.

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-api#2007] opened 2024-03-14 06:29 UTC
**Describe the bug**
Right now if you want to fetch the details of let's say `eventAdmin` with `title` as a sub-field from the User collection it will result in an error: "cannot return null for non-nullable field Event.title."

**To Reproduce**

1. Go to the Apollo GraphQL sandbox.  
2. Query for the user and provide the admin's ID as the `userId` in the variables.
3. Add `eventAdmin` as a field within the user query.
4. Include `_id` as a sub-field under `eventAdmin` and execute the query. You will observe no errors.
5. Next, include `title` under `eventAdmin` and execute the query again. You will encounter an error.
6. You can change `eventAdmin` with other fields other than `adminFor` like `createdEvents`, `createdOrganizations` etc. You will see a similar trend.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/110045644/9ec27a18-5dfa-409e-b065-74eaa64547cd)
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/110045644/2bd2aa33-3325-4e8f-bb48-01f1a5f06fc2)

**Expected behavior**
We want `eventAdmin` or any other field to behave like `adminFor` field i.e., showing all the queried data without any errors.

**Actual behavior**
When we include any sub-field other than `_id` under the `eventAdmin` or any other similar fields we get an error.

**Additional details**
This is a `good first issue`.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by sethum3001** [comment] 2024-03-14 14:02
Can you assign this to me?

**Comment by Paras-codes** [comment] 2024-03-21 13:17
can you please assign this to me

**Comment by Cioppolo14** [comment] 2024-03-21 23:52
@Paras-codes If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Paras-codes** [comment] 2024-03-22 04:53
Sorry sir I am a new comer and doesn't know the guidelines
I just asked for the opportunity as the issue was assigned last week and
was unsolved
I am Sorry for my mistake.

**Comment by NamitBhutani** [comment] 2024-04-08 19:58
This is not a bug, if the title field of the event is populated, its returned, same for all the other fields. Only if they are null , we get the behaviour as explained in the issue, and that is the Expected Behavior. Thus this issue can be closed.
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/26519624/09a7bf89-c127-4f28-a974-dc700048d13d)

**Closed** 2024-04-08 22:58 UTC
Labels: bug, good first issue
