### ISSUE TITLE
outdated google reCAPTCHA image in installation.md

### ISSUE THREAD

**Issue by sethdivyansh** [PalisadoesFoundation/talawa-api#2600] opened 2024-10-19 14:52 UTC
**Describe the bug**
Google reCAPTCHA page in installation.md file is outdated. It should be updated with the latest image.

**To Reproduce**

1. visit [https://github.com/PalisadoesFoundation/talawa-api/blob/main/INSTALLATION.md#configuring-google-recaptcha-in-the-env-file](url) or 
2. go to `Configuring Google ReCAPTCHA in the .env file` section in installation.md file.
**Expected behavior**
Latest image:
<img width="750" alt="image" src="https://github.com/user-attachments/assets/43fb5030-b92a-4d84-bdb2-59898241d95f">

**Screenshots**
Current image in file:
![image](https://github.com/user-attachments/assets/d0d8aae0-db55-4ed2-81c8-0b944e3bf5d3)

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by sethdivyansh** [comment] 2024-10-19 14:53
I would like to update the image on this page.

**Comment by srinidhisg88** [comment] 2024-10-21 04:42
Can you please assign this issue to me??

**Comment by sethdivyansh** [comment] 2024-10-21 19:35
@palisadoes, should I update the image?

**Comment by harshthakkr** [comment] 2024-10-24 21:10
As the issue is still open, can I work on this issue?

**Comment by Lipikacodes264** [comment] 2024-10-25 03:17
@palisadoes , I would like to work on this issue. Could you please assign this to me?

**Closed** 2024-10-27 19:45 UTC
Labels: bug, documentation, good first issue, feature request
