### ISSUE TITLE
Feature Request : Documentation Automation: Bridging talawa-api and talawa-docs repositories

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-api#1897] opened 2024-02-26 17:46 UTC
The current approach to generating and synchronizing documentation between the talawa-api and talawa-docs repositories faces challenges related to branch protection rules and the specification of source and destination branches.

*Current Workflow*:
talawa-api generates markdown files from inline tsdoc comments. These files are stored in a dedicated folder within the talawa-api repository. GitHub Actions encounters difficulties transferring these files to the talawa-docs repository, particularly due to some rules.

*Challenges*:
1. Branch Protection Rules: The develop branch in talawa-api is safeguarded, impeding direct commits.
2. Source and Destination Branch Specification: Complications arise in specifying source and destination branches for the documentation transfer.

*Proposed Solution*:
Trigger the workflow on a schedule or in response to push events on the develop branch of talawa-api.
Automate the generation of documentation files from inline comments (Already Implemented).
Commit files directly to the specified branch and folder location in the talawa-docs repository.

*Implementation Steps*:
Explore existing workflows for innovative insights and references.
Fork the talawa-api and talawa-docs repository to kickstart the documentation automation.
Conduct thorough local testing to validate the efficacy of the automation.

**Comment by tasneemkoushar** [comment] 2024-02-26 17:49
Kindly share your strategy or solution to this problem along with the request that the issue be assigned. You may ask your doubts here in the chat. Take help from @anwersayeed

**Comment by adi790uu** [comment] 2024-02-26 17:53
hey I would like to work on this

**Comment by Olatade** [comment] 2024-02-26 18:26
@adi790uu @AdityaRaimec22 

Kindly share your strategy or solution to this problem along with the request that the issue be assigned. You may ask your doubts here in the chat. Take help from @anwersayeed

**Comment by palisadoes** [comment] 2024-02-26 19:27
`cron` only works on the default branch. We need this to work with any branch type and a filter for develop

**Comment by adi790uu** [comment] 2024-02-27 16:06
@Olatade @tasneemkoushar I have tried the whole workflow so I have a question that when we merge the code from any other branch, is workflow triggered? If not we need to implement that and somehow Copy-docs-to-talawa-docs workflow is getting success but the changes are not reflected in my forked talawa-docs repo.

**Comment by anwersayeed** [comment] 2024-02-27 17:32
Hi @adi790uu @AdityaRaimec22 
@adi790uu Yes, the workflow needs to be triggered either by a push event or on scheduled basis, but we do not necessarily need the automated-docs branch, the task is to send the generated docs to the talawa-docs repository. Hence, it would be better if we generate the documents and copy it directly to the talawa-docs location.

**Comment by anwersayeed** [comment] 2024-02-27 17:39
> @Olatade @tasneemkoushar I have tried the whole workflow so I have a question that when we merge the code from any other branch, is workflow triggered? If not we need to implement that and somehow Copy-docs-to-talawa-docs workflow is getting success but the changes are not reflected in my forked talawa-docs repo.

When copy-docs-to-talawa-docs workflow runs, you will be able to see some logs. There could be several reasons if the changes are not reflected.

1. No changes detected (nothing to commit)
2. You may be running the workflow in the automated-docs branch, try running the workflow in the develop or from the default branch by manually doing some changes to the documentation.

**Comment by anwersayeed** [comment] 2024-02-27 17:42
We plan to not use this workflow "Copy-docs-to-talawa-docs". Either we find some alternative or write a script of our own.

**Comment by anwersayeed** [comment] 2024-02-27 17:45
The workflow for the generation of the documentation files is already written, what we are looking for is a workflow or simply a script that runs with the push/ scheduled event, that copies these files from directly after generating them to the talawa-docs without committing them in between to any repositories or other branches.

**Comment by adi790uu** [comment] 2024-02-27 17:47
@anwersayeed so what was the actual point of automated-docs branch?Can't we directly use copy-to-talawa-docs workflow when something is pushed to develop?

**Comment by adi790uu** [comment] 2024-02-27 19:04
@palisadoes so basically generating the docs in respective repos and then at a specific schedule get those changes from those repos?

**Comment by palisadoes** [comment] 2024-02-27 19:52
1. Possibly, especially if it can be proven to be reliable
2. The current methodology is temperamental, however we don't know why.

**Comment by adi790uu** [comment] 2024-02-27 19:58
Okay @palisadoes let me test this locally,I feel it's a good idea.

**Comment by adi790uu** [comment] 2024-02-27 19:59
@Olatade can you assign me this issue.

**Comment by anwersayeed** [comment] 2024-03-01 14:25
Hi @adi790uu, did you make any progress?

**Comment by adi790uu** [comment] 2024-03-01 14:34
@anwersayeed I am currently working on the cron job part on talawa-docs repository, it would fetch all the latest changes in docs from respective repositories at particular schedule.

**Comment by adi790uu** [comment] 2024-03-01 14:35
What's your opinion on this approach?

**Comment by anwersayeed** [comment] 2024-03-02 04:47
@adi790uu Yeah, a centralised point to fetch all docs seems fine to me. Can you prepare a demo with dummy files and repositories?

**Comment by adi790uu** [comment] 2024-03-02 05:04
@anwersayeed do you want me create an entirely new project and test as I was doing the testing and integration in talawa-docs repo.

**Comment by adi790uu** [comment] 2024-03-02 07:57
@anwersayeed here is the script : #!/bin/bash

git clone --depth=1 --branch automated-docs https://github.com/adi790uu/talawa-api.git

mkdir -p docs/talawa-api-docs

cp -r talawa-api/talawa-api-docs/* docs/talawa-api-docs/

rm -rf talawa-api

ls

git config --global user.email "adi37068@gmail.com"
git config --global user.name "adi790uu"

git add .

git commit -m "Pull changes from Talawa API automated-docs branch"

git push origin develop

**Comment by adi790uu** [comment] 2024-03-02 07:59
> @anwersayeed here is the script : #!/bin/bash
> 
> git clone --depth=1 --branch automated-docs https://github.com/adi790uu/talawa-api.git
> 
> mkdir -p docs/talawa-api-docs
> 
> cp -r talawa-api/talawa-api-docs/* docs/talawa-api-docs/
> 
> rm -rf talawa-api
> 
> ls
> 
> git config --global user.email "[adi37068@gmail.com](mailto:adi37068@gmail.com)" git config --global user.name "adi790uu"
> 
> git add .
> 
> git commit -m "Pull changes from Talawa API automated-docs branch"
> 
> git push origin develop

basically will use this in a workflow and run a cron job each time the talawa-api-docs folder in talawa-docs will be replaced by latest available docs from automated-docs branch. Is this the right approach for solving this issue?

**Comment by adi790uu** [comment] 2024-03-02 07:59
we can extend this for talawa-admin as well.

**Comment by anwersayeed** [comment] 2024-03-02 08:41
@adi790uu Not necessarily a new project, this is fine. Complete your script, test it, and ping me.

**Comment by adi790uu** [comment] 2024-03-02 10:38
@anwersayeed  
<img width="1465" alt="Screenshot 2024-03-02 at 4 07 14 PM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/f9bf055b-8c33-43ac-a158-108c25c1cb3d">
<img width="1465" alt="Screenshot 2024-03-02 at 4 07 23 PM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/4b7630b7-d9fb-4518-bb82-372454c94b7f">

the workflow is working in case there are changes in talawa-api-docs and pushing it to develop branch in talawa-docs

**Comment by adi790uu** [comment] 2024-03-02 10:39
this is the version of script used :

 #!/bin/bash

git clone --depth=1 --branch automated-docs https://github.com/adi790uu/talawa-api.git

mkdir -p docs/talawa-api-docs

cp -r talawa-api/talawa-api-docs/* docs/talawa-api-docs/

rm -rf talawa-api

git config --global user.email "adi37068@gmail.com"
git config --global user.name "adi790uu"

git add .

git commit -m "Pull changes from Talawa API automated-docs branch"

git push origin develop

**Comment by adi790uu** [comment] 2024-03-02 10:40
what change need to made here as I am using my credentials: 

git config --global user.email "adi37068@gmail.com"
git config --global user.name "adi790uu"

**Comment by adi790uu** [comment] 2024-03-02 10:41
similarly we can clone mobile and admin repos add the doc folders to talawa-doc and push them to develop.

**Comment by adi790uu** [comment] 2024-03-03 13:56
@anwersayeed I need your review on above so that I can proceed further with this.

**Comment by adi790uu** [comment] 2024-03-05 15:00
@anwersayeed sorry for bothering you but can you please review above, I have to proceed with the complete implementation and testing.

**Comment by anwersayeed** [comment] 2024-03-05 18:30
@adi790uu Please find me on the Slack channel. We may need to connect tomorrow for above changes.

**Comment by adi790uu** [comment] 2024-03-05 18:59
> @adi790uu Please find me on the Slack channel. We may need to connect tomorrow for above changes.

Okay @anwersayeed will ping you on slack

**Comment by palisadoes** [comment] 2024-03-11 21:57
How's progress on this?

**Comment by adi790uu** [comment] 2024-03-12 19:19
@palisadoes this will be completed soon, after @anwersayeed approve the latest changes I will create a PR.

**Comment by adi790uu** [comment] 2024-03-18 18:08
@palisadoes I have created a PR in docs repo this is for api-docs only mobile-docs and admin-docs will have different Pr's as suggested by @anwersayeed

**Comment by palisadoes** [comment] 2024-03-18 18:18
Please work with @anwersayeed and @tasneemkoushar to review and merge them

**Comment by adi790uu** [comment] 2024-03-18 18:55
Okay @palisadoes

**Comment by anwersayeed** [comment] 2024-03-19 09:19
I have provided some review comments, please address them. @adi790uu

**Comment by adi790uu** [comment] 2024-03-19 11:09
@anwersayeed I had to create a new PR as somehow the previous PR got closed, I have implemented the suggested changes in new PR.

**Comment by palisadoes** [comment] 2024-03-28 04:09
The documentation workflow isn't functioning. We really need it activated. Any news?

**Comment by adi790uu** [comment] 2024-03-28 04:19
@palisadoes yeah I am aware of the issue and in contact with @anwersayeed we are discussing about this.

**Comment by palisadoes** [comment] 2024-05-27 18:20
unassigning, inactive

**Comment by gautam-divyanshu** [comment] 2024-06-10 08:48
@palisadoes @anwersayeed what needs to be done now? Because I am little confused by this workflow, 

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/22595a06-1ff5-48a1-85b9-e0b41e7423fb)

**Comment by gautam-divyanshu** [comment] 2024-06-10 08:49
@anwersayeed Please help

**Comment by anwersayeed** [comment] 2024-06-12 07:55
@gautam-divyanshu Hi, tell me

**Comment by gautam-divyanshu** [comment] 2024-06-13 09:42
@palisadoes  @anwersayeed @tasneemkoushar 

**Progress-**
1. Push workflow runs when a PR is merged to develop branch
2. when PR is merged to develop then it creates a empty commit to automated-docs branch
3. then after empty commit copy-docs-to-talawa-docs workflow runs 

**it's working locally on my forked repo.**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/f6ac24cc-3d08-4bc7-b54a-bd3220cfce1f)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/c590b2b3-db53-4009-895f-d6dba3b825c8)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/0e4bc78c-17a3-4a41-b03c-f0c4f2d422bb)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/a6fe1f82-eccd-42f1-9bcb-1600d4279222)

**Comment by gautam-divyanshu** [comment] 2024-06-15 07:29
@anwersayeed can we close this issue also if mechanism is changed?

**Comment by tasneemkoushar** [comment] 2024-06-19 17:36
@gautam-divyanshu you don't need to do anything on this issue currently, 
It seems like @anwersayeed already fixed workflow issue of the talawa-api & talawa-admin, but I will keep this issue open for my observation period. The current cron job runs every Sunday, so for some more weeks I need to check if the automation.

I kind of missed out on the current flow but now I have documented the architecture and challenges. If you want to understand the current flow & the related challenge please refer [here(https://docs.google.com/document/d/19TwXb3prcF0dhS5mBFZxB7rmMbrmHfGknbuG5IIqXsk/edit?usp=sharing)

**Comment by gautam-divyanshu** [comment] 2024-06-19 18:10
@tasneemkoushar Okay, thanks for informing me.

I will try to run that locally to observe. I found an error in the generation of docs while I was working on my PR; that is deprecated code, and it is also present in the docs repo workflow.

and I will remove that.

**Comment by gautam-divyanshu** [comment] 2024-07-07 06:56
@tasneemkoushar can we close this issue now?

**Comment by gautam-divyanshu** [comment] 2024-07-08 16:07
@tasneemkoushar @anwersayeed I think cron job is working now, 

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/2014c12c-3031-43ba-9a1d-491f69bc9d21)

**Comment by gautam-divyanshu** [comment] 2024-07-08 16:15
you can see the changes here, 

https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/docs/talawa-api-docs/directives/directiveTransformer/authDirectiveTransformer/functions/default.md

**Comment by gautam-divyanshu** [comment] 2024-07-08 16:53
@palisadoes I will fix that later

**Comment by palisadoes** [comment] 2024-07-12 01:20
@tasneemkoushar @anwersayeed PTAL

**Comment by tasneemkoushar** [comment] 2024-07-13 06:50
@gautam-divyanshu I have check on few things, since I saw the workflow running and the folder getting updated. Would like to see the issue which you are facing. Let’s connect on slack

**Comment by gautam-divyanshu** [comment] 2024-07-13 10:04
@tasneemkoushar This section is being generated.
![image](https://github.com/user-attachments/assets/d8e17ee1-6b9a-4b6a-89f4-1c41cdb61095)

**Comment by gautam-divyanshu** [comment] 2024-07-13 10:05
The problem is with the sidebar. Because the folder structure has changed, we need to remove the sidebar from the API and admin documents.

**Comment by tasneemkoushar** [comment] 2024-07-13 17:49
@gautam-divyanshu but we need sidebar

**Comment by gautam-divyanshu** [comment] 2024-07-13 17:53
it is removed for api and admin section only, and sidebar is same for others

**Comment by palisadoes** [comment] 2024-08-11 17:52
Should this be closed?

**Closed** 2024-08-30 03:51 UTC
Labels: documentation, feature request, no-issue-activity
