### ISSUE TITLE
Fix Typescript Rules lint warnings

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-api#1201] opened 2023-03-19 15:12 UTC
**Describe the bug**
Currently, there are too many **Typescript Rules** ESLint warnings in the **develop** branch. 

Most of them are:-
"@typescript-eslint/ban-ts-comment",
"@typescript-eslint/no-explicit-any",
"@typescript-eslint/no-inferrable-types",
"@typescript-eslint/no-non-null-asserted-optional-chain",
"@typescript-eslint/no-non-null-assertion",
"@typescript-eslint/no-var-requires",

**To Reproduce**

1. Clone the **talawa-api** repository.
2. Install the project dependencies. (npm i)
3. In .eslintrc.json, change **Typescript Rule**, from line 49 to 54, from "off" to "warn", just like this:-
![pic2](https://user-images.githubusercontent.com/58592306/226185366-2143823c-1101-403f-a04e-f5080316cc02.PNG)

4. Run **npm run lint:check**

**Expected behavior**
Lint should report 0 Warnings and 0 Errors

**Actual behavior**
Lint now reports too many warnings.

**Additional details**
Multiple contributors can work together as there are too many warnings.

**Comment by tasneemkoushar** [comment] 2023-03-19 15:15
We can merge a contributor's pull request if they are able to resolve at least 10 warnings, but we won't mark this issue as resolved until all warnings have been fixed. This allows for the creation of pull requests by many users, which we will then merge one at a time. While the remedy is minor, it is possible that two persons worked on the same warning. In that case, whoever solves it first will have their modifications merged.

**Comment by ujwalkumar1995** [comment] 2023-03-19 18:37
Hey @tasneemkoushar 
Could you please assign me this issue?
I will try to resolve as much of the issues as I can.

**Comment by tasneemkoushar** [comment] 2023-03-20 05:34
> Hey @tasneemkoushar Could you please assign me this issue? I will try to resolve as much of the issues as I can.

@ujwalkumar1995 I have assigned this issue to you, please go ahead.

**Comment by nishtha981** [comment] 2023-03-22 15:24
Heyy
Can I be assigned this issue?

**Comment by SiddheshKukade** [comment] 2023-04-01 07:53
I’d like to get assigned to this issue.

**Comment by SiddheshKukade** [comment] 2023-04-04 07:29
Status: I currently have an exam going for this week. I'll get started on this in a few  days


Exam timetable floor reference 

 ![Screenshot_2023-04-01-14-00-23-920_com.google.android.apps.docs.jpg](https://user-images.githubusercontent.com/65951872/229719572-36c5f249-fea1-47ba-ac3d-43576b6f564e.jpg)

**Comment by anshgoyalevil** [comment] 2023-04-11 11:27
@palisadoes @tasneemkoushar 

Could you please assign this issue to me.
I can resolve at least 1500+ warnings.

**Comment by palisadoes** [comment] 2023-04-11 12:15
@SiddheshKukade I'm reassigning. We need to get this resolved.

**Comment by palisadoes** [comment] 2023-04-11 12:16
We also need to make checks fail on these warnings

**Comment by anshgoyalevil** [comment] 2023-04-11 12:18
@palisadoes Sure sir, Will enable that feature also.

**Comment by SiddheshKukade** [comment] 2023-04-11 13:00
> @SiddheshKukade I'm reassigning. We need to get this resolved.

@palisadoes no problem, my exams just finished today at 2 pm. I will get started on the other assigned issues.

**Comment by KrutikaBhatt** [comment] 2023-04-12 19:21
Hey @anshgoyalevil @palisadoes, there are many lint warnings and errors related to this. I have been working on adding some lint rules and am already on some progress in resolving these from files. I didn't check before that there was an issue already open for it. In case you haven't started working on it, will it be fine if I make a PR for this separately?

**Comment by anshgoyalevil** [comment] 2023-04-12 19:23
@KrutikaBhatt Yes sure. Go ahead. 

There are so many warnings and errors after enabling these rules. Your PR will be of great help.

**Comment by anshgoyalevil** [comment] 2023-04-12 19:26
I have started working on this issue, but upto the portion I have made PR upon, which is merged.

You may fix some warnings in your PR, just make sure to not close this issue with your PR, if all the warnings are not fixed up related to this issue

**Comment by KrutikaBhatt** [comment] 2023-04-12 19:30
Yes definitely, thanks alot!

**Comment by palisadoes** [comment] 2023-05-08 16:31
@tasneemkoushar Please provide guidance on this.

**Comment by KrutikaBhatt** [comment] 2023-05-08 17:24
@saiteja13427, there are still many warnings that need to fix. It was not feasible to solve all at a time thus we distributed the work among developers. Please feel free to go ahead and try to reproduce the error. It's fine if not all are removed and it would be great if we get to resolve the majority of them.

**Comment by saiteja13427** [comment] 2023-05-08 17:39
Sure, thank you.
Let me try and see how many can I fix.

**Comment by saiteja13427** [comment] 2023-05-19 02:06
I am working on this issue. There are a lot of warnings, thus it is taking time. Some new lint errors, I have fixed in #1334 itself.

**Comment by palisadoes** [comment] 2023-06-04 13:32
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by anshgoyalevil** [comment] 2023-06-04 13:38
@palisadoes Sir. Could you please assign me this issue 🌚

**Comment by palisadoes** [comment] 2023-06-04 13:41
Sure. Welcome back.

**Comment by anshgoyalevil** [comment] 2023-06-04 13:46
@palisadoes Uh oh! Couldn't find talawa-api project in my local machine. Un-assigning!

**Comment by git-init-priyanshu** [comment] 2023-09-17 11:47
Hey @palisadoes can you please assign this issue to me? Thanks.

**Comment by jaas666** [comment] 2023-10-29 01:04
There is an open PR #1412 for this issue.
Was it ever reviewed?

**Comment by parthiv360** [comment] 2023-10-29 12:48
@jaas666 Hey I have no idea regarding that. Maybe the one who created this issue is not active on this.

**Closed** 2023-11-12 17:09 UTC
Labels: bug, good first issue, no-issue-activity, dependencies
