### ISSUE TITLE
Update the LAST_RESORT_SUPERADMIN_EMAIL logic during setup

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1550] opened 2023-12-24 02:09 UTC
**Is your feature request related to a problem? Please describe.**

When running the setup command `npm run setup`:

1. If no `LAST_RESORT_SUPERADMIN_EMAIL` value has been configured then:
2. The `LAST_RESORT_SUPERADMIN_EMAIL` value should default to the `MAIL_USERNAME` value

This will make the installation smoother and allow easier registration.

**Describe the solution you'd like**
- See above

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment] 2023-12-24 04:03
@palisadoes I would like to work on this issue, please assign this to me.

**Comment by indiansamaltman** [comment] 2023-12-24 18:12
is this issue still open can i work on it ?

**Comment by Doraemon012** [comment] 2024-01-03 16:42
@palisadoes @Cioppolo14 
I've already raised a PR ( #1569 )for this issue which has been merged, but somehow the issue is still open. Please close this.

**Closed** 2024-01-03 16:46 UTC
Labels: good first issue, feature request
